---
# tasks file for patch-automation
# import tasks file to initiate the patching
- name: Defining patching Type
  debug:
    msg: "patching_type: {{ patching_type }}"

#- include_role: vsphere-snapshot


- name: Importing system patching via yum update with REBOOT
  include_tasks: yum_updatehost_with_reboot.yml
  when: patching_type == "SYSTEM_REBOOT"

- name: Importing system patching via yum update with NOREBOOT
  include_tasks: yum_updatehost_NO_reboot.yml
  when: patching_type == "NOREBOOT"




